### ISSUE TITLE
请教老司机一个问题？

### ISSUE THREAD

**Issue by baoyachi** [ruijun/awesome-gank.io#1]
<img width="711" alt="2016-07-19 11 52 26" src="https://cloud.githubusercontent.com/assets/10433001/16938103/6a3934e6-4da7-11e6-9220-ca37a1b95e78.png">

请教一下老司机，请问上面这张图片，怎么设置背景为手机的背景啊，一直想知道怎么做的？
👍

**Comment by ruijun** [comment]
@baoyachi [GankMM](https://github.com/maning0303/GankMM) 这个项目里面有设置为手机壁纸的功能，可以参考下。

**Comment by baoyachi** [comment]
@ruijun 我下载了最新版本，没找到啊？

**Comment by ruijun** [comment]
@baoyachi 
福利界面--点击图片--进入大图界面--下面就有两个设置按钮了呀

<img src="http://7xrn7f.com1.z0.glb.clouddn.com/16-7-19/7223247.jpg" width="270" height="486"/>

**Comment by ruijun** [comment]
@baoyachi 
福利界面--点击图片--进入大图界面--下面就有两个设置按钮了呀

**Comment by baoyachi** [comment]
![device-2016-07-19-142020](https://cloud.githubusercontent.com/assets/10433001/16940359/f7a2a47a-4dbb-11e6-83c2-8fa9ffdaa586.png)
@ruijun 我只看到了这个？

**Comment by ruijun** [comment]
@baoyachi 我理解错你的意思了，我以为你说怎样设置妹纸图片为手机背景图呢。  上图的应用介绍图带了手机外壳，我猜测作者使用第三方APP截图的。我所知道的[带壳截图](http://sspai.com/tag/%E5%B8%A6%E5%A3%B3%E6%88%AA%E5%9B%BE)就能实现这个。

**Comment by baoyachi** [comment]
@ruijun 谢谢，装逼收下了。哈哈哈……
💯
